const CHANGE_ACTIVE_STATE = 'CHANGE_ACTIVE_STATE';
const ADD_NEW_LANGUAGE = 'ADD_NEW_LANGUAGE';
const ADD_NEW_WORD = 'ADD_NEW_WORD';
const SET_CURRENT_LANG = 'SET_CURRENT_LANG';
const SET_NEW_TRANSLATIONS = 'SET_NEW_TRANSLATIONS';
const GET_TRANSLATION = 'GET_TRANSLATION';
const GET_ALL_TRANSLATION = 'GET_ALL_TRANSLATION';
const RESET_TRANSLATION = 'RESET_TRANSLATION';
const RESET_TRANSLATIONS_COLLECTIONS = 'RESET_TRANSLATIONS_COLLECTIONS';

export {
    CHANGE_ACTIVE_STATE,
    ADD_NEW_LANGUAGE,
    ADD_NEW_WORD,
    SET_CURRENT_LANG,
    SET_NEW_TRANSLATIONS,
    GET_TRANSLATION,
    GET_ALL_TRANSLATION,
    RESET_TRANSLATION,
    RESET_TRANSLATIONS_COLLECTIONS
}